# Site settings
title: "Tide-Hunter"
email: lexuszhi1990@gmail.com
description: "blog"
header-img: home-bg.jpg
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  lexuszhi1990

# https://help.github.com/articles/using-jekyll-with-pages/
safe: true
lsi: false
auto: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
# markdown: rdiscount
# markdown: redcarpet
highlighter: pygments
# highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-archives
# permalink: pretty
permalink: /:year/:month/:day/:title

paginate: 10
paginate_path: "/page/:num"

# google_analytics_tracking_id: UA-47869605-1

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md

sass:
  sass_dir: assets/stylesheets/_sass
  style: :compressed
