# Site settings
title: "Tide-Hunter"
email: lexuszhi1990@gmail.com
description: "blog"
header-img: home-bg.jpg
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  lexuszhi1990

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
# permalink: /:year/:month/:day/:title

paginate: 10
paginate_path: "/page/:num"

# google_analytics_tracking_id: UA-47869605-1

# https://github.com/jekyll-assets/jekyll-assets#how-to-use-jekyll-assets
assets:
  css_compressor: sass
  # cache: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

sass:
  sass_dir: _assets/stylesheets/_sass
